name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make lab
      working-directory: ./Lab7C/Lab7C
      run: |
        make Test
        ./Test
        gcov Test.c Source.c -r
        bash <(curl -s https://codecov.io/bash)
